### ISSUE TITLE
debug log file : execute

### ISSUE THREAD

**Issue by tsathoqqua** [fluffos/lima#10]
On startup the driver says:
```
call_out(0) nest level: 1000
==============================
Unable to open log file: "log   /execute", error: "No such file or directory". Use stderr only.
Initializing internal stuff ....
```
It looks like it adds a \t (tab) between log and execute? A strace confirmed that:
```
openat(AT_FDCWD, "log\t/execute", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
```
I've rewritten my line in config file without tabs twice now, so I'm not sure what's doing this.

**Comment by thefallentree** [comment]
it is because trailing tabs on the config line

**Comment by tsathoqqua** [comment]
Is it something I should fix or a robustness you want to build into the config file parsing?

**Comment by thefallentree** [comment]
The driver automatically  handles LF and CRLF lines, but i think tabs are
actually considered part of the config line, i'm not sure if we should ignore them.

**Comment by tsathoqqua** [comment]
The strange part is that I've rewritten the config line without tabs and I'm still getting them.
I'll try it again.

**Comment by thefallentree** [comment]
Did you solve this problem?

**Comment by tsathoqqua** [comment]
Stripped the file for all tabs using Emacs whitespace-mode, and there was a tab on the end of the line BEFORE the config line, and now the error changed to:
```
Unable to open log file: "log/execute", error: "No such file or directory". Use stderr only.
```
And it logs correctly now if I create a log directory where ever I run the driver. I thought it used to assume log/ was under the mudlib directory, but I must not remember that right Just think something is fishy with that parsing of the config file. Not sure I can pinpoint it.

**Comment by tsathoqqua** [comment]
Let's close this for now...

**Comment by thefallentree** [comment]
Yeah, one issue I know is that the current log directory is actually
relative to the :"working directory" when you invoking the driver, not the
"relative directory" in the lib dir, so I need to fix that
