### ISSUE TITLE
Stability and performance

### ISSUE THREAD

**Issue by tsathoqqua** [fluffos/lima#12]
Didn't know how else to reach out, so here's a non-issue issue! :)
The driver has been running stable for me, for almost an entire week. I've been developing and basically doing all the things I wanted and haven't spotted any further issues.

It seems FASTER than the old C driver, and runs smoothly! I'll keep testing, but so far I'd just like to say: Great job!

**Comment by thefallentree** [comment]
Glad to hear!

For higher bandwidth communications We could start to use Gitter.im/fluffos or forum.fluffos.info

I am also in touch with Adam from themud.org and he is starting to repackage old lib now

**Comment by tsathoqqua** [comment]
Alright, we're talking about FluffOS v2019 (and your work) on Intermud as well which you should join. I talked to Adam there for quite a while yesterday about my experiences with v2019 and Lima so far. If you haven't gotten access to igossip (imud_gossip) you probably should get it. You're welcome to sit on my dev mud and chat if you want. It's not open to players.

I'll kick off future threads on the forum, and post issues I find here :-)
