### ISSUE TITLE
terminal_colour() issue

### ISSUE THREAD

**Issue by tsathoqqua** [fluffos/lima#5]
Hey,

I've updated (file wise) and updated (inside the MUD) all the remaining failing files I could find including ones that does not load by default by the library. On top of this I had to add a simul_efun to fix an ansi issue that has appeared (it was also in a previous Fluff driver I was using (called 2.28.3 by Quixadhal).
```
//:FUNCTION terminal_colour
//Override of efun to avoid some driver issues.
string terminal_colour(string str, mapping m, int wrap, int indent)
{
    str = efun::terminal_colour(str, m, wrap, indent);
    str = replace_string(str, "\e[0;10m", "");
    str = replace_string(str, "\e[49;49m", "");
    return str;
}
```
If the underlying cause of that could be fixed it would be brilliant, and the sefun override could be removed again. The escape codes up there are added to the end of strings when using the terminal_colour efun, and they seem to serve no purpose. They screw up length calculations of strings containing escape codes so the length is returned wrong.

```
//:FUNCTION colour_strlen
//colour_strlen(s) gives the length of the visible portion of s.  Colour
//codes (e.g. %^GREEN%^) are ignored.
int colour_strlen(string str) {
    return strlen(terminal_colour(str, ANSI_D->query_translations()[1]));
}
```
i.e. colour_strlen("%^YELLOW%^Hello!%^RESET%^") is not == strlen("Hello!") but strlen("Hello!\e[0;10m\e[49;49m") which is quite different.

Apart from that things seem to be running. I have 3 commits in the branch.

**Comment by thefallentree** [comment]
So, I checked the source code and terminal_colour has been adding those RESETs string at least for 10 years now. so I would say lima code should just deal with it :-D

I think your solution works and we should probably just fix the documentation for terminal_colour instead. https://www.fluffos.info/efun/contrib/terminal_colour.html

**Comment by tsathoqqua** [comment]
Alright, fine by me :-)

**Comment by tsathoqqua** [comment]
Oh btw:
https://github.com/quixadhal/fluffos/blob/master/src/packages/contrib.c#L644

(I'm not sure I would fix this now, but rather focus on keeping compatibility with the old beast as it is first, and once this beast spins and roars, then start to consider improvements like fixing these old things)
