### ISSUE TITLE
Migrating crypt algorithm

### ISSUE THREAD

**Issue by tsathoqqua** [fluffos/lima#9]
I can see that the FluffOS v2019 enforces a stronger encryption algorithm which is fantastic, but what's the best way to migrate old users? Ideally, I'd like to have something like:

```We've upgraded our encryption to secure your personal data on the mud. 
Please enter your old password: *********
Thank you.
Now please enter a new password: ***********
Again: ***********
Your password has been updated, logging you in ...
...
```

But I guess that requires that I can somehow confirm that the old password is correct? Is that possible right now or what's the migration path for old users?

**Comment by thefallentree** [comment]
depending on what algorithm you currently use ,  base on your current cipher text , if it starts with "$1$" ,  "$2$" etc,  just call 
`crypt(password, ciphertext)` and if it works,  just call `crypt(password, "")`  and use the new cipher text returned to "upgrade" user.

If your cipher text starts with "!" something, it is MD5, which you should call `old_crypt(password, ciphertext) ` to verify , after success just call `crypt(password, "")` to get new cipher text.

**Comment by tsathoqqua** [comment]
My passwords look like:
```
password "oofj`ecf!eiooljaognd`cfoffhcec`eadmibmbff"
```
I'll see if old_crypt can make something of that. Perhaps it would be useful for oldcrypt() to show up on https://www.fluffos.info/efun/strings/crypt.html or https://www.fluffos.info/efun/ so people would know about it.

Ah, it's oldcrypt() says the driver source files. Got it.

**Comment by thefallentree** [comment]
yeah , that is the MD5 password that old_crypt will work

**Comment by tsathoqqua** [comment]
Works, upgraded all my MUDs to run fluffos v2019.2020041301 . Seems to work.
Find me at plexus.themud.org 4242 if you need to chat at some point in time. It's not open to players.

**Comment by Penniman** [comment]
I'm not running Lima my solution might not be a drop in alteration but in my MUD's /secure/lib/connect.c class I added the following blurb.  It converts password hashes to the new hash algorithm at time of login.

  hash = Player->GetPassword();

  // 2020-02-07 Convert Fermat's custom crypt()-based password hash to SHA-512.
  if (!hash || (hash[0..2] != "$6$" && hash == oldcrypt(pass, hash)))
  {
    Player->SetPassword(crypt(pass, ""));
    hash = Player->GetPassword();
  }

  if (hash != crypt(pass, hash))
  {
    receive("\nInvalid password.\n");
    ...
  }

**Comment by tsathoqqua** [comment]
Here's where I ended up
```
/*
** Name and password processing
*/

nomask int matches_password(string str)
{
   if (password[0..2] == "$6$") // 36 == $
      return crypt(str, password) == password;
   else
   {
      if (oldcrypt(str, password) == password)
      {
         write("(Upgrading your password hash to SHA)\n");
         old_password = password; 
         password = crypt(str, 0);
         return 1;
      }
   }
   return 0;
}
```
I'm storing the old hash in old_password for a while until I know I don't have to switch back to the old driver :-)

**Comment by tsathoqqua** [comment]
```
nomask int matches_password(string str)
{
#ifdef OLD_PASSWD_COMPAT
   if (password[0..2] == "$6$") // 36 == $
#endif
      return crypt(str, password) == password;
#ifdef OLD_PASSWD_COMPAT
   else
   {
      if (oldcrypt(str, password) == password)
      {
         write("(Upgrading your password hash to SHA)\n");
         password = crypt(str, 0);
         return 1;
      }
   }
   return 0;
#endif
}
```
was what I submitted into the fluffos/lima repo.
